//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFF.Freedom.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DFF.Freedom.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 当前应用程序未初始化，请按照统一应用程序功能说明进行配置。 的本地化字符串。
        /// </summary>
        internal static string ApplicationUninitializedExceptionMsg {
            get {
                return ResourceManager.GetString("ApplicationUninitializedExceptionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数组参数“{0}”必须为拥有一个元素。 的本地化字符串。
        /// </summary>
        internal static string ArrayParaLengthZeroExceptionMsg {
            get {
                return ResourceManager.GetString("ArrayParaLengthZeroExceptionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 业务处理逻辑“{0}”，任务对象“{1}”。 的本地化字符串。
        /// </summary>
        internal static string AutoTaskWrapModelStringFormat {
            get {
                return ResourceManager.GetString("AutoTaskWrapModelStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按任意键退出...... 的本地化字符串。
        /// </summary>
        internal static string CmdWaitPromptMsg {
            get {
                return ResourceManager.GetString("CmdWaitPromptMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在枚举类型“{0}”的枚举项上未发现定义的附加信息，请检查此枚举类型的附加信息定义。 的本地化字符串。
        /// </summary>
        internal static string EnumDescriptionInfoNotExistExceptionMsg {
            get {
                return ResourceManager.GetString("EnumDescriptionInfoNotExistExceptionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在枚举类型“{0}”的枚举项“{1}”上定义了多个关键字为“{2}”的附加信息。 的本地化字符串。
        /// </summary>
        internal static string EnumDescriptionInfoRepeatExceptionMsg {
            get {
                return ResourceManager.GetString("EnumDescriptionInfoRepeatExceptionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数“{0}”必须为枚举类型。 的本地化字符串。
        /// </summary>
        internal static string EnumParaNotMatchExceptionMsg {
            get {
                return ResourceManager.GetString("EnumParaNotMatchExceptionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 给定的表达式类别与预期不匹配，预期为“{0}”类别，实际为“{1}”类别。 的本地化字符串。
        /// </summary>
        internal static string ExpressionCategoryNotMatchExceptionMsg {
            get {
                return ResourceManager.GetString("ExpressionCategoryNotMatchExceptionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前的 IO 操作属于事务性操作，但在当前上下文中未找到相关的核心事务对象。 的本地化字符串。
        /// </summary>
        internal static string KernelTransactionNotFoundExceptionMsg {
            get {
                return ResourceManager.GetString("KernelTransactionNotFoundExceptionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志适配器提供程序“{0}”未找到，请检查程序集是否存在。 的本地化字符串。
        /// </summary>
        internal static string LoggingAdapterTypeNotExist {
            get {
                return ResourceManager.GetString("LoggingAdapterTypeNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在类“{0}”中定义的公共属性“{1}”没有 get 定义或 get 访问级别不足。 的本地化字符串。
        /// </summary>
        internal static string NotCanReadPropertyInType {
            get {
                return ResourceManager.GetString("NotCanReadPropertyInType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在类“{0}”中定义的公共属性“{1}”没有 set 定义或 set 访问级别不足。 的本地化字符串。
        /// </summary>
        internal static string NotCanWritePropertyInType {
            get {
                return ResourceManager.GetString("NotCanWritePropertyInType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型“{0}”不包含参数列表为“{1}”的公共构造方法。 的本地化字符串。
        /// </summary>
        internal static string NotExistCtorInType {
            get {
                return ResourceManager.GetString("NotExistCtorInType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型“{0}”不包含无参数的公共构造方法。 的本地化字符串。
        /// </summary>
        internal static string NotExistNotParamCtorInType {
            get {
                return ResourceManager.GetString("NotExistNotParamCtorInType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性“{0}”在模型“{1}”中不存在。 的本地化字符串。
        /// </summary>
        internal static string NotExistPropertyInModel {
            get {
                return ResourceManager.GetString("NotExistPropertyInModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在类型“{0}”中未找到公共属性“{1}”的定义。 的本地化字符串。
        /// </summary>
        internal static string NotExistPropertyInType {
            get {
                return ResourceManager.GetString("NotExistPropertyInType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数“{0}”不能为非正整数。 的本地化字符串。
        /// </summary>
        internal static string NotPositiveIntegerParaExceptionMsg {
            get {
                return ResourceManager.GetString("NotPositiveIntegerParaExceptionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在当前操作系统中不支持 Restart Manager 特性。请参考 https://msdn.microsoft.com/en-us/library/windows/desktop/cc948910(v=vs.85).aspx 的本地化字符串。
        /// </summary>
        internal static string NotSupportedRestartManagerMsg {
            get {
                return ResourceManager.GetString("NotSupportedRestartManagerMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对象容器适配器提供程序&quot;{0}&quot;未找到，请检查程序集是否存在。 的本地化字符串。
        /// </summary>
        internal static string ObjectMartAdapterTypeNotExist {
            get {
                return ResourceManager.GetString("ObjectMartAdapterTypeNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数”{0}“给定的值内容超出了以下有效范围：{1}。 的本地化字符串。
        /// </summary>
        internal static string ParameterChoiceScopeOverflowExceptionMsg {
            get {
                return ResourceManager.GetString("ParameterChoiceScopeOverflowExceptionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数“{0}”不能为空引用(null)。 的本地化字符串。
        /// </summary>
        internal static string ParaNullExceptionMsg {
            get {
                return ResourceManager.GetString("ParaNullExceptionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数“{0}”提供的路径信息在实际磁盘中找不到。 的本地化字符串。
        /// </summary>
        internal static string PathArgumentNotFoundExceptionMsg {
            get {
                return ResourceManager.GetString("PathArgumentNotFoundExceptionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定的路径“{0}”必须是一个文件，不能为目录。 的本地化字符串。
        /// </summary>
        internal static string PathNotDirectoryExceptionMsg {
            get {
                return ResourceManager.GetString("PathNotDirectoryExceptionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 业务处理逻辑（容器：{0}，标识：{1}）发生异常，信息为：{2}。 的本地化字符串。
        /// </summary>
        internal static string ProcessLogicExceptionMsg {
            get {
                return ResourceManager.GetString("ProcessLogicExceptionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0024000004800000940000000602000000240000525341310004000001000100255851f99521ea25af7a3e19ffbd38a0f5b5769a93cb6fb05f71d7c809f3aab2a26d67acd77845b47b58b4e5afe0ee0ca61f1958f153d76badba0ffdc3faa9c333f86fbf024ce0b936d446024d8c59d3327931fee87391c8c8c6c19bec3a9fb6532de42570707614357fa49e946ef2a8db054ab8e92146a6f8cd6f86f666acc9 的本地化字符串。
        /// </summary>
        internal static string PublicKey {
            get {
                return ResourceManager.GetString("PublicKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 40064b2782c60d97 的本地化字符串。
        /// </summary>
        internal static string PublicKeyToken {
            get {
                return ResourceManager.GetString("PublicKeyToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通过 Restart Manager 特性获取应用程序及服务进程信息时发生错误，失败代码“{0}”。请参考 https://msdn.microsoft.com/en-us/library/windows/desktop/cc948910(v=vs.85).aspx 的本地化字符串。
        /// </summary>
        internal static string RestartManagerGetListFailMsg {
            get {
                return ResourceManager.GetString("RestartManagerGetListFailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通过 Restart Manager 特性注册资源时失败，失败代码“{0}”，请参考 https://msdn.microsoft.com/en-us/library/windows/desktop/cc948910(v=vs.85).aspx 的本地化字符串。
        /// </summary>
        internal static string RestartManagerRegisterFailMsg {
            get {
                return ResourceManager.GetString("RestartManagerRegisterFailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在执行当前处理前，请首先运行方法“{0}”。 的本地化字符串。
        /// </summary>
        internal static string RunConditionNotEnough {
            get {
                return ResourceManager.GetString("RunConditionNotEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前操作需要配置节组“{0}”的支持，请在当前应用程序配置文件中进行设置。 的本地化字符串。
        /// </summary>
        internal static string SectionGroupNotExist {
            get {
                return ResourceManager.GetString("SectionGroupNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前操作需要配置节“{0}”的支持，请在当前应用程序配置文件中进行设置。 的本地化字符串。
        /// </summary>
        internal static string SectionNotExist {
            get {
                return ResourceManager.GetString("SectionNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数“{0}”不能为空字符串（String.Empty）或空引用（null）。 的本地化字符串。
        /// </summary>
        internal static string StringParaEmptyOrNullExceptionMsg {
            get {
                return ResourceManager.GetString("StringParaEmptyOrNullExceptionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数“{0}”的内容必须与正则表达式“{1}”匹配。 的本地化字符串。
        /// </summary>
        internal static string StringParaNotMatchExceptionMsg {
            get {
                return ResourceManager.GetString("StringParaNotMatchExceptionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数“{0}”或其类型与预期的类型不匹配。 的本地化字符串。
        /// </summary>
        internal static string TypeNotMatchExceptionMsg {
            get {
                return ResourceManager.GetString("TypeNotMatchExceptionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据实体接口“{0}”中数据字段“{1}”缺少特性“{2}”标记。 的本地化字符串。
        /// </summary>
        internal static string UndefineDbFieldAttributeExceptionMsg {
            get {
                return ResourceManager.GetString("UndefineDbFieldAttributeExceptionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在数据实体接口“{0}”中缺少特性“{1}”标记。 的本地化字符串。
        /// </summary>
        internal static string UndefineDbTableAttributeExceptionMsg {
            get {
                return ResourceManager.GetString("UndefineDbTableAttributeExceptionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法识别的父表达式，当前表达式的父表达式必须为“{0}“类别。 的本地化字符串。
        /// </summary>
        internal static string UnrecognizedParentExpression {
            get {
                return ResourceManager.GetString("UnrecognizedParentExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数“{0}”的类型必须为值类型。 的本地化字符串。
        /// </summary>
        internal static string ValueParaNotMatchExceptionMsg {
            get {
                return ResourceManager.GetString("ValueParaNotMatchExceptionMsg", resourceCulture);
            }
        }
    }
}
